### ISSUE TITLE
Support Scala 2.11.x

### ISSUE THREAD

**Issue by amirkarimi** [bahmanm/persianutils#7]
Publish the lib against scala 2.11.x

**Comment by khajavi** [comment]
<div dir=rtl>
سلام،
هنوز کتابخانه برای ۲٫۱۱ منتشر نشده.

**Comment by amirkarimi** [comment]
Hi,

No it's not published to Maven but you can get the source from [here](https://github.com/amirkarimi/persianutils) and publish on your system using `publish-local` sbt command.

**Comment by bahmanm** [comment]
انتشار یک نگارش تازه روی سوناتایپ واقعا پردردسر و کنده. اصولا بین‌تری[1] به اندازه‌ی کافی تو ایران شناخته شده هست که اون جا منتشر کنم؟

[1] bintary

**Comment by bahmanm** [comment]
بعد از رفع #9 نگارش ۲.۰ رو با بین‌تری منتشر می‌کنم.

**Comment by roohi66** [comment]
حیفه لایبرری به این توپی آپدیت نشه
یکسری وارنینگ دپریکت کم کم مشکل ساز میشه

**Comment by bahmanm** [comment]
Done in release 2.0 --next step would be 2.12.x
