### ISSUE TITLE
ایراد تبدیل از میلادی به شمسی

### ISSUE THREAD

**Issue by SoheilJafari** [bahmanm/persianutils#9]
از 1346/10/11 تا 1346/12/30
وقتی به میلادی تبدیل میشه درسته ولی وقتی از میلادی به شمسی تبدیل میشه یک روز کم نشون میده

**Comment by bahmanm** [comment]
ممنون. بررسی می‌کنم.

**Comment by bahmanm** [comment]
اصلاح شد. ممنون می‌شم آزمایش کنین.
master 1199f02

**Comment by SoheilJafari** [comment]
سپاس، حتماً در اسرع وقت نتیجه را اعلام خواهم کرد
